name: Docker Image CI

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: docker-web-image-1

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUBUSERNAME }}
        password: ${{ secrets.DOCKERPASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t mohd1995/ec2-web:latest .
        docker images  # List images for debugging purposes

    - name: Push Docker image to Docker Hub
      run: |
        docker push mohd1995/ec2-web:latest
